### PR TITLE
Signal order layers ,Minor changes

### PR DESCRIPTION
**Pull request by All4Gis**
Sorry for so many changes.

Changelog:

   Changed dialogs details (hide help button)
   Management of login dialog buttons
   Management of Import By Id dialog buttons
   Added signal to combobox orderByCombo
   Change wait cursor when load some layer

### CODE REVIEW

**Comment by enricofer** [comment]
Hi Francisco, I'm very pleased to merge your PR. I love the waiting cursor!
I see you deeply work inside UI, and having a look to your changes before merging I noticed you solved how feedback from a busy process with QtGui.qApp.processEvents(). Neat.
I will use it to display a busy progress in message bar during while processing layers. Never stop learning!
Two questions:
1) the plugin is not well tested for multiple concurrent access. Are you interested to help me test it?
2) many people working under windows are reporting me a nasty bug: https://github.com/enricofer/gdrive_provider/issues/1. In which system are you working with the plugin? Did you find any connection issue?
big thanks

**Comment by All4Gis** [comment]
thanks for accepting my PR.
I'm working in windows 10,but I have not tried the multiple acces,then Happy to assist you with that.
And the second question,I will try to reproduce and solve it.

**Comment by All4Gis** [comment]
Tested for a multiple concurrent acces and works perfectly,I have tested it manually, I have not created a test file.

**Comment by enricofer** [comment]
Thanks for testing it. I was thinking to a further massive test involving other interested users. I will schedule it as soon as possible.

**Pull request merged**
